-- MySQL Script generated by MySQL Workbench
-- Tue Sep 16 20:11:36 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mao-na-massa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mao-na-massa`;

CREATE SCHEMA IF NOT EXISTS `mao-na-massa` DEFAULT CHARACTER SET utf8;
USE `mao-na-massa`;

-- -----------------------------------------------------
-- Table `Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cliente`;

CREATE TABLE IF NOT EXISTS `Cliente` (
  `usuario_id` INT UNSIGNED NOT NULL
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Contratacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Contratacao` ;

CREATE TABLE IF NOT EXISTS `Contratacao` (
  `servico_id` INT UNSIGNED NOT NULL,
  `cliente_id` INT UNSIGNED NOT NULL,
  `profissional_id` INT UNSIGNED NOT NULL,
  `preco` DECIMAL NOT NULL,
  `status` CHAR(32) NOT NULL
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Favorito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Favorito` ;

CREATE TABLE IF NOT EXISTS `Favorito` (
  `cliente_id` INT UNSIGNED NOT NULL,
  `profissional_favorito_id` INT UNSIGNED NOT NULL
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Notificacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Notificacao` ;

CREATE TABLE IF NOT EXISTS `Notificacao` (
  `id` INT UNSIGNED NOT NULL,
  `cliente_id` INT UNSIGNED NOT NULL,
  `mensagem` TEXT NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `foi_lida` TINYINT NOT NULL DEFAULT 0
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Portfolio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portfolio` ;

CREATE TABLE IF NOT EXISTS `Portfolio` (
  `id` INT UNSIGNED NOT NULL,
  `profissional_id` INT UNSIGNED NOT NULL,
  `arquivo_id` TIMESTAMP(6) NOT NULL,
  `arquivo` BLOB NOT NULL,
  `descricao` CHAR(255) NULL
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Profissional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Profissional` ;

CREATE TABLE IF NOT EXISTS `Profissional` (
  `usuario_id` INT UNSIGNED NOT NULL,
  `biografia` CHAR(255) NULL,
  `categorias` TEXT NOT NULL,
  `faixa_preco` INT NOT NULL,
  `avaliacao_media` DECIMAL NULL
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Servico` ;

CREATE TABLE IF NOT EXISTS `Servico` (
  `id` INT UNSIGNED NOT NULL,
  `cliente_id` INT UNSIGNED NOT NULL,
  `categoria` TEXT NOT NULL,
  `descricao` TEXT NOT NULL,
  `localizacao` CHAR(255) NOT NULL,
  `avaliador_id` INT UNSIGNED NULL,
  `nota` TINYINT NULL,
  `comentario` TEXT NULL
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario` ;

CREATE TABLE IF NOT EXISTS `Usuario` (
  `id` INT UNSIGNED NOT NULL,
  `nome` CHAR(128) NOT NULL,
  `telefone` CHAR(25) NOT NULL,
  `email` CHAR(255) NOT NULL,
  `senha` VARCHAR(512) NOT NULL,
  `foto` BLOB NULL
)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
